#!/bin/bash


pkill -f lemonbar &> /dev/null
pkill -f stalonetray &> /dev/null
pkill -f subscribe &> /dev/null

lego_signal "kill"

pkill -f lego &> /dev/null

# notify-send -t 2000 "GoLemon" "All subprocesses terminated"
