#!/bin/bash

# pamac checkupdates -a | sed '/Out of Date/Q' | sed '/^\s*$/d' # print everything until Out of Date and remove empty lines
# pacman -Qu ? maybe


stamp=$(date +"%H:%M");
pamac_raw=$(pamac checkupdates -a )
pamac_output=$(echo "$pamac_raw" | sed '/Out of/Q')
out_of_date=$(echo "$pamac_raw" | sed -e '1,/Out of/ d' | wc -l)
num_packages=$(echo "$pamac_output" | grep 'available update' | awk '{print $1}')
aur_packages=$(echo "$pamac_output" | grep AUR | wc -l)
normal_packages=$(($num_packages-$aur_packages))

if [[ $num_packages -gt 0 ]]; then
    message="\uf187 $num_packages"
    if [[ $aur_packages -gt 0 ]]; then
        message="$message[$aur_packages]"
    fi
    echo -en "%{F#f9dc2b}$message%{F-}"
fi
