#!/bin/bash


if [[ -f /tmp/current_redshift ]]; then
    current_var=$(cat /tmp/current_redshift)
    fancy_var=$(python -c "print(str($current_var/1000) + 'K')")
    color=$(python -c "print('#' + 'FF' + '{:02x}{:02x}'.format(int(255*($current_var/6000)),int(255*($current_var/6000))))")
    echo -en "%{F$color} $fancy_var%{F-}"
fi
